### ISSUE TITLE
Вагонна група. Додати новий реквізит!

### ISSUE THREAD

**Issue by Romito91** [ShamatienkoYaroslav/1c_port_config#17]
В документі "ЗаявкаПодачиВагонов" таблична частина "Вагоны", потрібно додати реквізит "Грузоотправитель" тип данних Контрагент. 
P.S. Використовується для звіту "Сводка по вагонам" в частині "Погрузка". Звіт з урахуванням потрібних змін уже готовий.

**Comment by ShamatienkoYaroslav** [comment]
Виконано.
