### ISSUE TITLE
Друкована форма "Повідомлення" доопрацювати

### ISSUE THREAD

**Issue by ShamatienkoYaroslav** [ShamatienkoYaroslav/1c_port_config#21]
Перевязати під відвантаження імпорту. Заповняти наряд з строк, номер накладної з номера вход. док. документа. Розтягнути підвал. Тягнути адресу контрагентів із адреси контрагента.

**Comment by ShamatienkoYaroslav** [comment]
![img_20150224_153438](https://cloud.githubusercontent.com/assets/7289255/6350402/20643954-bc3c-11e4-99c4-d4d4ebfc505c.jpg)

**Comment by SlavaAtamanskiy** [comment]
Виконую

**Comment by SlavaAtamanskiy** [comment]
Виконано.                                                                                                                                        Адресу контрагентів тягну, як юридический адресс контрагента, якщо він не заповненый, тягну просто адресс контрагента.

**Comment by SlavaAtamanskiy** [comment]
Виконано з доповненнями: Адреса контрагентів - просто адреса контрагента.

**Comment by ShamatienkoYaroslav** [comment]
Необхідно доопрацювати. є помилки.
