### ISSUE TITLE
Доопрацювати обробку "Генеральний акт"

### ISSUE THREAD

**Issue by ShamatienkoYaroslav** [ShamatienkoYaroslav/1c_port_config#29]
Доопрацювати обробку "Генеральний акт", а саме кнопку "Предварительный генеральний акт".
![img_20150224_153416](https://cloud.githubusercontent.com/assets/7289255/6350328/82f148ba-bc3b-11e4-83eb-778d5d3838e3.jpg)
![img_20150224_153424](https://cloud.githubusercontent.com/assets/7289255/6350338/9579aff4-bc3b-11e4-8351-b84478b53b11.jpg)

**Comment by SlavaAtamanskiy** [comment]
Виконую

**Comment by SlavaAtamanskiy** [comment]
Виконано
